dist: bionic
language: java
jdk:
- openjdk8
- openjdk11
- openjdk15
branches:
  only:
  - develop
  - master
  - 3.x.x
before_install:
- export TZ=Europe/Helsinki
install: true
script: mvn clean verify -q -Dgpg.skip
notifications:
  email:
    recipients:
    - aare.nurm@nortal.com
    - siim.suu@nortal.com
    on_success: change
    on_failure: always
